name: cash_stepper
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  barcode_widget: ^2.0.4
  bloc: ^8.1.2
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.0
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: any
  build_web_compilers: ^4.0.3
  flutter_driver:
    sdk: flutter
  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  test: ^1.24.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
