name: cash_stepper
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  barcode_widget: ^2.0.4
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.9.3
  collection: ^1.17.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.0
  dropdown_button2: ^2.3.9
  file_picker: ^5.5.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  firebase_storage: ^11.2.8
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_cache_manager: ^3.3.1
  flutter_datetime_picker_plus: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.16
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.6.0
  from_css_color: 2.0.0
  go_router: ^11.1.4
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  image_picker: 1.0.4
  intl: ^0.18.1
  json_path: ^0.6.3
  mime_type: 1.0.0
  page_transition: ^2.1.0
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  plugin_platform_interface: ^2.1.6
  provider: ^6.0.5
  rxdart: 0.27.7
  shared_preferences: ^2.2.1
  sign_in_with_apple: ^5.0.0
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.0
  stream_transform: 2.1.0
  timeago: ^3.5.0
  url_launcher: ^6.2.1
  video_player: ^2.7.2

dev_dependencies:
  build_runner: any
  build_web_compilers: ^4.0.3
  flutter_driver:
    sdk: flutter
  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  image: ^4.1.3
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  test: ^1.24.3
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: assets/images/app_launcher_icon.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # - assets/videos/
    # - assets/audios/
    # - assets/lottie_animations/
    # - assets/rive_animations/
    # - assets/pdfs/

  fonts:
    - family: Lexend Deca
      fonts:
        - asset: assets/fonts/Lexend Deca-Medium.ttf
        - asset: assets/fonts/Lexend Deca-Regular.ttf
