name: cash_stepper
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  barcode_widget: ^2.0.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.3
  collection: ^1.18.0
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  dropdown_button2: ^2.3.9
  file_picker: ^6.1.1
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  firebase_messaging: ^14.7.14
  firebase_storage: ^11.6.6
  fl_chart: ^0.66.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.3.1
  flutter_datetime_picker_plus: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.17
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  json_path: ^0.7.0
  lottie: ^3.0.0
  mime_type: 1.0.0
  page_transition: ^2.1.0
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.1
  rive: ^0.12.4
  rxdart: 0.27.7
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^5.0.0
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.2
  stream_transform: 2.1.0
  timeago: ^3.6.1
  url_launcher: ^6.2.4
  video_player: ^2.8.2

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  flutter_driver:
    sdk: flutter
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  image: ^4.1.6
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3
  test: ^1.24.9
  very_good_analysis: ^5.1.0

# 아이콘 생성 원할 시, dart run flutter_launcher_icons
flutter_launcher_icons:
  android: ic_launcher
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  macos:
    generate: true
  image_path: assets/images/app_launcher_icon.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # Attempted to generate localizations code without having the flutter: generate flag turned on.
  # Check pubspec.yaml and ensure that flutter: generate: true has been added and rebuild the project.
  # Otherwise, the localizations source code will not be importable.
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie_animations/
    - assets/rive_animations/
    # - assets/audios/
    # - assets/videos/
    # - assets/pdfs/

  fonts:
    - family: Lexend Deca
      fonts:
        - asset: assets/fonts/Lexend Deca-Medium.ttf
        - asset: assets/fonts/Lexend Deca-Regular.ttf

# flutter_gen_runner는 자산, 폰트, 색상 등을 위한 Flutter 코드 생성기로, 문자열 기반 API를 없애줌.
# String 기반으로 자산 경로를 사용하는 것은 안전하지 않음.
# build_runner와 FlutterGen을 패키지의 pubspec.yaml 파일에 추가하고,
# Homebrew 또는 Pub Global activate를 사용하여 FlutterGen CLI binary를 설치.
# https://pub.dev/packages/flutter_gen_runner
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 120 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    enabled: true
    outputs:
      class_name: Palette
    inputs:
      - assets/colors/primary.xml

# Usage:
#   dart run import_sorter:main -e
import_sorter:
  emojis: true

analyzer:
  errors:
    deprecated_member_use_from_same_package: ignore
    invalid_annotation_target: ignore
  exclude:
    - lib/bootstrap.dart
    - lib/firebase_options.dart
    - bin/cache/**
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "**/gen/*.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/injector.config.dart"
    - "**/test/*.dart"
