name: cash_stepper
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  barcode_widget: ^2.0.4
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.9.3
  collection: ^1.17.2
  crypto: ^3.0.3
  dropdown_button2: ^2.3.9
  file_picker: ^5.5.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  firebase_storage: ^11.2.8
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  flutter_datetime_picker_plus: ^2.1.0
  flutter_localization: ^0.1.14
  flutter_localizations:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  flutter_spinkit: ^5.2.0
  font_awesome_flutter: ^9.1.0
  from_css_color: ^2.0.0
  go_router: ^11.1.2
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_path: ^0.6.3
  mime_type: ^1.0.0
  page_transition: ^2.1.0
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  sign_in_with_apple: ^5.0.0
  smooth_page_indicator: ^1.1.0
  stream_transform: ^2.1.0
  timeago: ^3.5.0
  url_launcher: ^6.1.14
  video_player: ^2.7.2

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: any
  build_web_compilers: ^4.0.3
  flutter_driver:
    sdk: flutter
  flutter_gen: ^5.3.1
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  test: ^1.24.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
